// Package mgmtapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package mgmtapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8bXPbNpp/BcPdD9tZSZYVe1tr5j4ostPqtkk8tro70zrnQOQjCQ0EsABoW+fTf7/B",
	"CymQBCXKdtL0rp1+iCnwwfP+hgd8jGK+SjkDpmQ0fIwEyJQzCeaP1zi5gt8ykEr/FXOmgJl/4jSlJMaK",
	"cHb0q+RMP5PxElZY/+uvAubRMPrL0Rb0kf1VHl0rzBIskgshuIg2m00nSkDGgqQaWDTUeyLhNt10oglT",
	"IBimXw6BfEd0DeIOBMoXdtwGljOAY7srpvT9PBr+smdXWKw06pvOY5QKnoJQxPKYsIUAKW+J3naOY9AP",
	"qxiZJahYgvgcqSWgmcGiF3UitU4hGkZ6xQKEZlwm8cLusAsvS8dPdq2mUbOeCEii4S85iE4Axw/Flnz2",
	"K8Qq2ugnRFH96Ho8ef8OpVgtu9LSjWLOpBJZrClyaGsk7fbfg7pyavefTpZlHs0Kbu+npUaFe7mOcb69",
	"oV4DB5atDN3prYAFkUoYBYs6UcLvWfVZzAVUn2m08cL+5TFkRCm/hwTZ/ZDhqyc1qQRhiwpCVjkUrA6R",
	"oYaRb/ojkUorCnabz7zNpbc7FgKvo06UMfJbBhO7oxIZbDrReFQXRgxC3d5hShKi1vtw+1e+btOJUk5J",
	"vPeNS7tKm1tmBbXPoLNCnu6N20+wviVJyxf/CevJeU1r8s1rQAs6OhVOhBRsrNk2144K6oxMiFSELTIi",
	"l5DcMrwya2o6QWRyi/cqwUQmI1nlAaYLbhT7Aa9SoxQX4/PrUUjznsO6TnS4OlTYHeBFQbkHPkBeDXXP",
	"7jz2I9+lhiS1xCTgeYiUGYh9ZPlibq+4pbca1c9h0EBVrNFuRdtrQTQqNQL3ytq8bcXcjhtVVWy9/tla",
	"ZMyzxjoPsMdFww8UP4mXk/OyVc3x6SvcP8FRJ5pzscIqGkZLeOg689olukkCTD8yeNascryE+FPAc2CF",
	"94sN4k/neqHJcBQmtJ5ZjJKE6H9iigizqBObUGyJC+GVO6sytHd4ZVKTJWCqlijWGJRhGUEgSRYMBMJ3",
	"mFA8oxDaQQB2qUB5jyvzHM25sPDRHBOaCdiPs1RYZbJFeqhXVTXLeSQHo2Ml4GnTD5bkcU5yQG9yceic",
	"sWD7pSdXHXO3EN8IAE3mCm1XI72toV1nf1U21/a0SAUiuH5D1nmbZww+YJMptEpDrK5uKnnFcxlfcNwh",
	"7aeZ2WqFxdrD2C5GmCUe8g1syTPOOnuWBdt24euYW8XXveyjCeKOxIW4KnZWx46nAS/tFweFmp8MQon/",
	"QflC1YHmEbec6TtKLrHmscvolzwNoW/hlrzjcXc+7/eH/eHxcV+nT1jpAisaRv91c5P8vfu3X3B33u+e",
	"fXg87pxsht88DjblR9/8j173V8+NTq7Pu6PrPb7zR774Ee6A1rlJ88cV9eeLBWELZH/uFOVAArNsYXgy",
	"1+kGmHrwg+9u3C8VFCq8tWBDWeJlkRhX7RQTdkvJHBRZlUUffTtY9ld9uXfXCozg9oLPKKwCYaYpaqBl",
	"tsIMCcCJ9t8IHlKKmdFpJFOIdYhDiiO1JBLxOM6EALYtW1O7IVJLrBCRaAk0nWdUv0G5iY3+Km3NC3IH",
	"CCfGjjhDS36vF6eCxwBJD/1bEKWAIcLQBVtQIpfmrQI/7TGBLQgDELKDMplhSteIcYVkRhQkZgXjDCmI",
	"l4zEmGpf8gmWnCYgrEfRqzV6lPw3JOVwM+aMga1tFTdOeoYlIM3xBPFMhdSTMKkwC5X7I/TT1QQJmIPl",
	"mmVTruvSMKfgciN3Owh6ix6arU38YAuE0Vxga7sFMIG4QDKbdXWxbiXmiWedQg+9xWs0A5RJSCoCEpwr",
	"uymRxUuEWfx4JmJAMU8qkfnILTyKC551jUX9RfFPwLralLpacF3Dva7lXpFVZYJ0C87sjvJlpk6XgH6Y",
	"Ti/zGKExQwtgILCW/2xt0OaCLAhD0nZ+bKDdpcIl2k77rzrRCj+QlfYbp2dnnWhFmP3ruN8P+Wrn0Ooa",
	"IJdcaOUsIlxdML+30udx7Se2M5GzDzSFc5xRLUM845kazihmn6JOG923nQm6rhqBzw/EmV5gtc80Ch+U",
	"x7c7kkCCRpeTHnqfptwps29J1nsRhq7ejLvfftf/toOI8U4MiFqCQAJivloBS+y7M11S5ogahmt+pZww",
	"pX/G1kd2C3EkPM608dl9GBdoQfnMiMTSV+R1JTG3M54DTKQpv7KqGIoPee+yFh/gISWu9TV83CKQYAXG",
	"ekPqsORp+86WzoUCCWWL/oRF2VatFEt1m6UaraQ9ovq5VHiVtn0lVItugXR8blVwclwJdlCLfGtPXeoo",
	"bqjygSW3B/aRDmUysIVNmitJlXmeW6IjpqTVxyHHKBUW6vZZqWwSVcB0fDYUGNdaAk/mfa0rMDs5TU5O",
	"kr1dAff+nnz22lTNddlieRuX24wHtKrKJlwWnd0QbZcgsrKuc7Z23Qvt8qZXY5Q3WMruatAfDLr9427/",
	"ZNo/G56eDV+9+tlnxm77E3GLRuT0amz1zyxntwuBY7hNQRCeBJKAq7FNZLBESmRS2RyGSO33zavIvtox",
	"lGmNpViBVIbIGDPG1Q3Ls6ESkN6Npxozzing+lFEyQVU5FZQHKbF7/9xpgSnSOfckDdTvLIyqKKlU6+6",
	"f8gfl/llVqMVSHO2sM/jFYVRaHeXlOU1VYqltEaQwELgxHjBOSZUPyzVVtuVlV6LS+QKz2KykeCpyvW2",
	"D1nt7j67VA6S63fHSy7huzP0+gydnKHxAA3e6P/Pxuj8HPXP0WCETr9FozN0foG+uzA/naI3r1D/DB33",
	"0fmxbzgyxTEk3bIzqVI9vRoHnEWmllwQnYXcwS2WBxwzFZGhGo7NQdjLgCqpX+gspL1DeJlmsnfysCWz",
	"E2JjGXnPXLXr2BNAplfjJ7fnHcF15GuBrR0iVmUr569Ywi3LVjMbf3aHbiKTFl0qCYJgGgL6qr68bnpR",
	"p4RUFV6F/aHA6hHNU075Yr23M1t98V+eipUZxri6xXNVoex5AVHDnMGcC6gBPX4i0GqTe7tDxyPBY2ZO",
	"sQuTdW5uNq5PVq9pLydFhWNTrDyOuUIyqke4vMQcXU60LYKQFla/1+8da57wFBhOSTSMXvX6vYHtLi6N",
	"CI7sebf59wJUQ7d7i41bbitOLAB9Yvye5VVi7DDKwwyaLgEJkBlVUicGuhycE6pAbJsJJvlEo+sOIrUB",
	"Dp1emJP4yigHer1GrlLuIEwpyphJGorze2lwE6AywSDReBCJZrDEd4SLHJN4idkCEnRP1NJA/4gp/Wg2",
	"/Wg82i1WH1GKBV6BAmHa5Fp9TfowSaJh9D2o145/mqf5QjPnUskSDZWuI8vnOZqWQzhJDOEaL8JimiWA",
	"7glNYiwSif7W/wbNuFoWejG5PjdIjq69FlU5p6w0k4lG4bcMhPbQ9lSqmvS3GwsqgnyVvre2hVOMUdj5",
	"iVxsuSC2ZL9ndF1XpvxtnTNTal51gFzLgmptvCeUavkV4vVJbzeX8iHMk2KUpx03qmNB+yeSSBnZQRiN",
	"+iCRj1HRO/vH6emrU6971g+FhFpyn9faCCt0vyTxsiYdIwpjAD00maOMSTAuwHWNTI9PIe0wtb/UdYFO",
	"9J2RmQbTEkuEGYL5HGKFyNxY1n/MMZXwsVb8HHePj7uD0+nxYDjoD0/7vdPBzw06m1tliR/tXHhdNtbO",
	"cpoFLLBIqBYXn/vVnDkmE2D/0NB7DchhSkt4Fa08Q3eo6qni9O8lmB6a4kiA9uPgusRCIS4SEOhvWMbA",
	"TKN6VrjAb5ow0tCfidJIKUFmmQK9X64u1p9rLdGoWdEbjckAffT9ykfbo5R5fHD+z2+sWwcxJ0Kaw7Ky",
	"dpQqwaAT40KFKaz2jvKSqgTSbzxV/GHl9V2zfYWSfeiUB0MH/f5BA5mhcb5DB9zq9cImmH6Ez7RXWMVL",
	"rV2laN/TQE8sMSEMCqKPvFFYMwpqO/ONaYQWAV5If/5Qv5YnJUePrrXUJcnGSpeCCpwEnJvnNfjbyL4g",
	"d8CKRtXkvB7KLQjHwz3BfLrt0aHJeTk3KZp32nXqx4SlmXLGQaQ9stA2vsQMYQ9M3kjXhJPEZEgYpQLm",
	"5MH4IB0QC/H4ntoyJfe/1hvPM2rSBfOb/4IuBxLEjSsnAlF3mKu3t9ZN7KHB8QDN1gpyBByJOFYZpj4f",
	"TT8HHlLKEyjcirFUnWJ6hloIMvKzaVsytBxJ9hupUq2Nh5DEuIqA6Z3U1cQNljqGIZnFMUg5zyhdP03F",
	"O9Fpm1eK6eyyTTRobcgoOuHk/HsbmP161cyybg8+fcA78tffSeNnmbI6XRxV+dpW3hAecKzoGnGWb9zJ",
	"kxKT2xtUiKxkhV+hYvZfbEg/PBcecO8lp1garXm2Y89VsLRFpX/S1sUfzSifNVaiwZ30G7o4uLx4i4DF",
	"XKdGO/T8td6gput/ODV56Kaw6s4JrTQ5uvq/1xffT96hy9H0B3R98f3bi3dT8/iGGcZZPvR6vRtmHl+8",
	"Ow+tjfYokZHU51GemZVRUGti7KlHTcZjHH1GaxuPgqZVBBH0Psfn+YyZbG0UmUEAw6bxqOcxJk7TTyTn",
	"y/aIpEUrx5VwdK0DOrmD+nxvQ4Pnhu3o8IQaPDbh76E3mdCVzYoL6Nww7cL14hRLqZMcLBSJM4qFGwwg",
	"ttDaVqgG6S2ON8whWRSqCEsbdnpohFw5k+NTzDWYskoHB51L3TCfZ51K/WezI9u+03/fYeKO7kzCU9c8",
	"n/81/xKs8Z/ceHnxwrhNMVurFJ8b11oOyxYj+fWyprGIqWuzZ5ANCLqRkb8f5hLymcDg/TirmGJ3ORTA",
	"tW7hnSjlUgXn0hEODOe7atseu0rFhbPT2sobZmfSrH1guQ2jkNgpatd3c1SgGU/WNVjOHIu+3B0IXdwn",
	"CC80QZbQ6dUY2a45moEZtEuS7XiRj2rAwi659E3MhWCQ6jVP1s+Lk+OLq+nkzWQ8ml640De69u8flCNl",
	"ffVOUOPRIaDCxjsjDBvLrFpuTeV84dVEXUtbNjUDPn65UOnZbR3P+vUOvxKzivE1WKzG4OxLYlBnDKYC",
	"cLJG8ECkkhUnos0/bPxba2qRLxw9mhfzHsvO3Lu+3ZwLhF1/xd362R8jG0JkOeXOsXpywl1cyfqsRZi9",
	"EtdGml9dFGqU6mFa065sq6tO7qtc3JmtFUhb0D1JqcK13dekWH+wcNTGQVXqwK9cr6u1ZUm5OZuTxc7y",
	"0q7YK3IFD+oope6mbC2Hbg7gn6eWvBSEKdtfm75/+yOyhGbueEtrY6mq5KtVUW5v73gFTftSgASm/Gt2",
	"5TkzhClni20bHh4gzhQk9btzNWa7i2Of0XFXLriF5LHjTtoLlPgJKS6JyNJOvjzym3JGHvnMSJOGTuwN",
	"qz+Wfr7GksQ+c1GKF+C1PSo9B3uhScpGraV8cVRcXmtiVXHv7TNqWLHHF+Ol9ny0ckGvxqNOlGYBplxX",
	"mNKmwHo5fuTXCv39dxUrf2QpXbeRktZk13VuPZ3lj+M3zWgdPpuFWYLAzhtVLiigCZMpxMod+yTkjiTe",
	"AaF0idyKm2NKhQmFBN0RuA+6/Ouc2gNnqULXJb78BNQUxIowTNEOpAY5UoNGpEqXLw5D6Yu05Eo3aA5o",
	"ylUmC0qa2vt6+3MBbD1jdY8q1vr0sYXSdZqDhxfyG2hPOsv1t/68swtlJ9V6gqH82v/rOYbg3SvDwq+j",
	"bXb6pTFo/BRd86yFz72gRT9z5KJkTzui3f+B0+gDvyyYf+Ov6YS5pNcNNdfX1WfYfxeyfbw4ZAaitGNj",
	"N22X9v05D3GJ1TK/Wfr0qYiSJL7qnlgTvo1KWtynbaqk3Y3bz+ky7A5fumNGgkMYo2vkt0HzL35oPvnd",
	"iq69d+puhTbNbVjuPrWBbnrlZbtvaJNbDo6Lg8A/W9YvNbp0UI9ZeXfomsypuGf3GQ2q2OP3aEI7CorL",
	"QaNrlPNldzdaibhFJ8RdRbd+bmpOQq84V2jst71tZwJwvDS3qQ6+zdYw69RD71N7L5Ku7cW06dW46K44",
	"x2zuN0kF2EwWmfsyHt6cQbghPtXUtwvV9VGjUi+hqPMDX9qpfZTOhmXtCKOve1aouB18QFPCbTujZj7l",
	"Re85aHhNXkDE8ojI5JHIZNOdPepadtOVj/Zy7qZl8tek2g0RYCriVoejVlmaM7qdF5YLDSnD1AS2A3rc",
	"GqZlVjuoobvSn7PEmV6NQ1o3vRq/4MC13uRJ+nVIhdGkZNVZMdNjMcVGo/a1Pp7/UwOfmIhNr8YuD/r5",
	"19H9+19H/3g7vbifVLKm7aooqKIvnB8VEAO6aj9wcJfrQiZoNIyWSqXDo6PHJZdqM3xMuVAb84kJQbSj",
	"tt8eLcYhi9t+PMbUPDbTkqLy86v+yelA2+SHAo3aV1zuQKyV6VAKoOZzd4qHu9XVKjiqnwbsgja+vPzn",
	"BK2wMgrkgbOMqQMbmywIjS4nCB6KbwtZYC458bFySVMAKZaYAWvp4+Qd3m+/FROA6g6iNx82/xsAAP//",
	"qwaMCQ1jAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
