env:
  GOPROXY: "http://localhost:3200|https://proxy.golang.org|direct"
steps:
  - label: "E2E: default :go: :man_in_business_suit_levitating: (scion, ping)"
    if: build.message !~ /\[doc\]/
    parallelism: 20
    command:
      - echo "--- build"
      - make
      - echo "--- start topology"
      - ./scion.sh topology -c topology/default.topo
      - ./scion.sh run && sleep 10
      - echo "--- run tests"
      - ./bin/scion_integration || ( echo "^^^ +++" && false )
      - ./bin/end2end_integration || ( echo "^^^ +++" && false )
    plugins:
      - scionproto/metahook#v0.3.0:
          post-command: |
            echo "--- Shutting down SCION topology"
            ./scion.sh stop
            echo "SCION topology successfully shut down"
    artifact_paths:
      - "artifacts.out/**/*"
    timeout_in_minutes: 15
    key: e2e_integration_tests_v2
    retry:
      automatic:
        - exit_status: -1 # Agent was lost
        - exit_status: 255 # Forced agent shutdown
  - label: "E2E: failing links :go: :man_in_business_suit_levitating:"
    if: build.message !~ /\[doc\]/
    parallelism: 20
    command:
      - echo "--- build"
      - make
      - echo "--- start topology"
      - ./scion.sh topology -c topology/default-no-peers.topo
      - ./scion.sh run && sleep 10
      - echo "--- run tests"
      - ./bin/end2end_integration || ( echo "^^^ +++" && false )
      - ./integration/revocation_test.sh
    plugins:
      - scionproto/metahook#v0.3.0:
          post-command: |
            echo "--- Shutting down SCION topology"
            ./scion.sh stop
            echo "SCION topology successfully shut down"
    artifact_paths:
      - "artifacts.out/**/*"
    timeout_in_minutes: 15
    key: e2e_revocation_test_v2
    retry:
      automatic:
        - exit_status: -1 # Agent was lost
        - exit_status: 255 # Forced agent shutdown
