// Package mgmtapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by unknown module path version unknown version DO NOT EDIT.
package mgmtapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbaXPjNtL+K11MPrypUJePN7G+aWTPRJU5XLaSrUrsdUFES8IMCTAAaFvr1X/fAkBS",
	"vCRRnsmsp2pT+TAigWbjwdONPuAnLxBRLDhyrbzhkydRxYIrtD9eEXqFfyWotPkVCK6R23+SOA5ZQDQT",
	"vPdRCW6eqWCJETH/+l7i3Bt63/U2onvurepda8IpkfRCSiG99XrtexRVIFlshHlD802Q6UfN23SikTtG",
	"qdncfBfNz1iK2DxxulKmNOOLhKkl0jtOIjtGr2L0hp7SkvGFt/Y9puidk7ZLy4miI2WGq2T2EQN99wlX",
	"dyRcCDMRH0kUh0bsxfj8euT59a8UpzG6FxM3+ldcTc7N7HsSMsr0at+837NxBieDGZNIveGfTVjkKy+I",
	"b1heTfVb39NM29UW4IfinuXrF3amWcF4SRiv7xFTKkG5b1nFbd5gedCsCh6ZCD/TYMuqAqN2q7W9ksyo",
	"Ulvg3r22s902t0OjSsXW4z+bRYxu6LCBriC4gKLFA4JnYTk5L1vVnJwek/4J8XxvLmREtDf0lvjYSc1r",
	"19ZNKHLzyOpZs8pfRNywZVyjnJMAS0qcHOXzzYAFyoOdRxXNzPw2Hyzgd0n0EhQuIuQaliJuAsvJLUE1",
	"6Mzn/f6wPxwM+p7vxURrlMaL/vPmhv7Y+b8/SWfe75zdPg38k/Xwh6ejdfnRD/82474vYDq5Pu+MrvcA",
	"+VYs3uI9hnU0w+xx2am/FYsF4wtwr30PeRJZR4WzZGExmRvfg/ZQuPULK0zfVFSoYOvE3jZgdinFLMSo",
	"4bhATViDpiNYJhHhIJFQMgsR8DEOCbdHHagYA0M40AL0kikQQZBIiTxAEHPQS4TYfRD0kmhgCpYYxvMk",
	"NDNCYZlaHEU4hQW7RyD0nhkhHJbiwQyOpQgQaRf+IZnWyIFxuOCLkKmlnZXrNxcSkC8YR5TKh0QlJAxX",
	"wIUGlTCN1I7ggoPGYMlZQEJQmnzCpQgpSmWlmdFGvZD9C2nXK27AWHCOgV2+FkCJJjOiEDSLkIJIdBM/",
	"GFeacGdSVXh/u5qAxDk61BxMGdmUBSdHeSu6PmB30YXZCgilhlcE5pI448mFSRASVDLrxMa27I4VtmcV",
	"YxfekRXMEBKFtLJBUgjtPspUPolxp59IZIAQCIplqHrpwF6QY9axlP5Oi0/IO4bLHbNxHYtex6GX+7hE",
	"sk6OTGNUoYlOVB3U6RLhl+n0EtwAqxkskKMkZv9nK6u2kGzBOCiU9ygtKXZTuLS20/6x70XkkUXGcE/P",
	"znwvYtz9GvT7Tc4y9Sh1BqilkIacUUTkqmY3dmP+26S/Rmnt8TdO7gkLzTebNsQ9MCuckyQ0e0hmItHD",
	"WUj4J89vw/2Es78SDFdVIyjiAYKbAY59Ngp/1AXc7hlFCqPLSRc+xLFIyVy0JOe9GIer1+POTz/3f/KB",
	"We/EkeklSpAYiChCTt3cmQnwMkUt4AavWDCuzWvifGQn3w4qgsQYn/sOFxIWoZjZLXHrS+lW2eZ2xnOA",
	"iVTDPmcvGRWbzodrd+TWzwd8jJkkbueeNgpQotFabxMdliJ2IYXGaG+UYIKRnEIekZKsrOvcny04lV0M",
	"GRKl75LYqEXbK2qeK02iuO2UpshwI8QvolXRKUWlEOpcjycf3kNcDHj2RInpirfE3Mjp3YFZ3aEgI1/o",
	"ZUNUY59nlpgupsTqQZNjVJpIffdZsaSNzIti/CIMuca1AP3Z2Ndi9NnJKT05oXtj9HT+noCyXBWob3H2",
	"uIy/HQ0RKkUW+0mbB5f1NRbz79Iyfz6DV2dwcgbjIzh6bf4/G8P5OfTP4WgEpz/B6AzOL+DnC/vqFF4f",
	"Q/8MBn04HxSRUTEJkHbKAFUxmF6N6ysniV4KyYxnvcc7ktZlWjmYnO1VFxMI+aVElfajqdqy19CmV+Mv",
	"VPSwRlGobWyW6TfBWFa+YCnTq/E+o5hejZ9dAEgXXFe+ZqztFHGULWthIvQ7nkQzV17Y7Y6Yoi1SX4WS",
	"kbBJ6HF9eD319fySUlV5FfibnMVm0b8XmFJeNxf6jsx1RUHvqH901OkPOv2Taf9seHo2PD7+o2ieO89K",
	"I3OGcyGxJnTwTKEVeApf8AtLKGCSrRhilEzQOijrdZpD13xkFsmOLid5EOZOgXOCkWNV6WB2j814Y04o",
	"lZPT7/a7A4OHiJGTmHlD77jb7x65qsPSwt8r1H/sgwXqhlOTKe0iWZt36HAFJDB2WS8fKRcjE4nwiYsH",
	"nsa1N9wEwVKENplhAXbBpEASVRJqCAg3AeychRqlS39cUaMLrxNpwt1ISPRvuOBoB8dEKSAQE6lZkIRE",
	"ppGuCbhZhEA0PCxZsHRKb3S84amSRj/reIAoYDxOdBdGMBMiRMIzffJAXQuQqBPJgYThDS9i5oPEBZE0",
	"RKXSsILJdNPNb5OLWCJ0b8zGGerboGtCvaH3BvW4iL/ZGEki1CiVN/zzyWMG/b8SlMY7ugL5pirVrnqf",
	"hyPN0iwId0SX5LWziGaBJAxLstJpKbTeen3rlzsWR/3+Qa2KVsdfoeJbOwPrDQzLb9FQDLUn6MlOBdMc",
	"6MfDeipZkatBmQl3xCx1VFzmXTLFuq6+p8nCEMcL4vgT827XvhcL1WDQI0qBNNR+0yRUy0RpUFrI1E5r",
	"I2+4K7I4+yAKLi/eAfJAmJ+UaJLlvukqYCboqiYrNUd4YGFoDO4epTlCKJCFWZBbqDldnK+FGdrKEaWb",
	"fLmoaoOFXQpVNDHPuXFU+pWgqx27+tiJMerMWVg5Qjrmv1cXbybvYXxxNZ28noxH0wv79IaProvl7W63",
	"e8Ptm4v35w2jd4oajw4R1Wy8M8aJtcyq5dYoV9y82lZ7xaNPywTXNQMefLFeY9Fu63rWuwcqCQJUap6E",
	"4coR4yVYrNHg7GtqUAeGhBIJXQE+MqVVxYkY8282/o01NXiTtV+OF3pPdmKH0fXW0OENbnFXNrQhtpTO",
	"IW0q7T8jtxyRJp7ZHEGZVjXm+oew0Ib8n3tY7f1Kq918cafQ1l09jDW9WShmz6BO5qvSc2e20qjAyHoe",
	"qV4ZLV40sb6x46iNg7Jb/83w2qm7hdyCz9miQOM619yIvVuu8VH34jC9iFGLobcf4Nf5MQgfso8XwG3C",
	"KlelV7gyVEbjUjKuXW9j+uHdW3ALTZx4k63ZfkAOiYhMcuowyTLbbYhMXI/428LjFVEsALM0E2EZDGKy",
	"QLANpLzRU8hxXUdYqa0ohWLRy9vv26DKO/d/41GUf+OrYWksLaxcMahh5Htx0gDKdQWUNgH9l8MjuxhR",
	"/P6u4Phb3qXrNrtkmJy2JlqUkOr9jC0lo6ZKkWoqFdmxmkhtW57IKYyuqx0emHAVY+BUYJyye0YTEm5U",
	"cIFDZLJMd88EKdwzfOg2xQ7X2WprQUNlU6xW6f0cMW/sN1UvBDXVVCp9o4MLP5W7BygjxkkIO5Q6ypQ6",
	"2qpUqXt1mEpfpQRUakEeUASKiA6WhvANTO2+3HpQg7YFY00fVay195T+K0vhKIaoG26AnNvnW74DD0y7",
	"SquLu7PHk/O68ThBWQt/j/lMNwYMk/P8+kTh012YzFOTjhMN9yRMEJhy91VQGsfCgRSEZLcoAsEVo9aD",
	"EIglztmj9R4kDDcEKDspYl2DUZ8al8SUkZMoNC7XeA/7rj5tRhRSEDytDGfe1KjiStTMRViDI5vHZMqk",
	"iyWBLrgpyLIZfIxDQdEbzkmo0G/KVTY7++xspdRRV3plPYNi1kU02PBJQyujqXltIXwZZZrTr62BRmk8",
	"77W70ZXdqC8a9E5Ta7Rof3f6XHhqWEU2l/Xq8neddnVrfZEs/HLhVrbupmirzutCWtB9sXnt/ssk7c+L",
	"dsWbhi9urd7sYl9zjeabY2CLQs7laPoLXF+8eXfxfpoWVCyIl0Qvs6s55QpMwwyvFWdfdA1mm77bSKpl",
	"0CL9CIlGpVPhU1vuvhJCw7hY23DpAJJgaYL3LenJ4Q3tLnyw+pAwXPk21JhejfOUJkUDKTCuNBLbPrbX",
	"SAt6C46q0UymZvXt7KPeTy4F8Hlw3XA/uHKXKLMF4/m8l90Qzu//HJAJpJ+dhbYJWQr+n5lP5zQ08raU",
	"Ew2Pe0zRJ6boujN7MgHkuqOe3PWbdUuPu43aW6rhUxm0qoA7smx3ozuvJOUMKcs0C2wndNBapgOrndSm",
	"21B/Z1wxvRo3sW56Ne5+mbpaSrDn8euQY30byaoXAmxiY0/4rexr3YP5HwOfGVdMr8ZpcPDHx9HDh4+j",
	"/383vXiYVGKJzSivkaLVmOHzabq1teKuMN5nXEhk6A29pdbxsNd7Wgql18OnWEi97pGY9e4H9i6pZMZf",
	"W8SW+dWX7E897J+O2Mf2ZoysvD4eDE6PjGne5tpU+T+2RU97NQ8f3R9uzFapNaSBgD2fs4ahq5HWa3AX",
	"9yhX2lYZJIb2b360aK44VSPZA6WNLy9/nUBEtOVjUTeL8/p2/Z8AAAD//3R00jdQPgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
